version: '2'
services:
  web:
    image: node:11
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/
    command: bash -c "npm install -g nodemon && nodemon --exec \"node server -d\""
    ports:
     - 3000:3000
