---
- hosts: app
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'docker', 'docker-compose']
    - git:
        repo: https://github.com/ColinRoye/{{ serviceName }}
        dest: /app
        force: yes
    - name: Run mix commands
      shell: cd /app
               && echo y | sudo docker system prune
               && sudo sysctl -w vm.max_map_count=524288
               && npm install
               && sudo nohup npm run prod&
      become: True
